version: '3.7'

services:
  # Сервисы для VM1
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

  apache1:
    image: httpd:latest
    networks:
      - backend

  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    ports:
    - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_password
    volumes:
      - mysql_master_data:/var/lib/mysql
      - ./master.cnf:/etc/mysql/conf.d/replication.cnf
    command: --server-id=1 --log-bin=mysql-bin --binlog_do_db=mydb --bind-address=0.0.0.0
    networks:
      - backend

  # Сервисы для VM2
  apache2:
    image: httpd:latest
    networks:
      - backend

  mysql_slave:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_MASTER_HOST: 192.168.140.132
      MYSQL_MASTER_USER: repl_user
      MYSQL_MASTER_PASSWORD: repl_password
      MYSQL_MASTER_PORT: 3306
    volumes:
      - mysql_slave_data:/var/lib/mysql
      - ./slave.cnf:/etc/mysql/conf.d/replication.cnf
    command: --server-id=2 --relay-log=mysql-relay-bin --read-only=1 --skip-slave-start
    networks:
      - backend

  # Сервисы для VM3
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - backend

  elk:
    image: sebp/elk:latest
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - elk_data:/var/lib/elasticsearch
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_master_data:
  mysql_slave_data:
  elk_data:
