filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/apache2/*.log

output.logstash:
  hosts: ["192.168.140.134:5044"]
  ssl.enabled: false

setup.ilm.enabled: false
setup.template.name: "apache"
setup.template.pattern: "apache-*"

- module: nginx
  access:
    enabled: true
    var.paths: ["/var/log/nginx/access.log*"]
  error:
    enabled: true
    var.paths: ["/var/log/nginx/error.log*"]
