input {
  beats {
    port => 5044
  }
}

filter {
  if [fileset][name] == "access" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "apache-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "changeme"  # Пароль по умолчанию в образе sebp/elk
  }
}
