global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: 
          - '192.168.140.132:9100'
          - '192.168.140.133:9100'
          - '192.168.140.134:9100'

   - job_name: 'nginx'
    static_configs:
      - targets: 
          - '192.168.140.132:9113'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
