global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.140.132:9100', '192.168.140.133:9100', '192.168.140.134:9100']

  - job_name: 'apache'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.140.132:9117', '192.168.140.133:9117']

  - job_name: 'mysql'
    static_configs:
      - targets: ['192.168.140.132:9104', '192.168.140.133:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['192.168.140.132:9113']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.140.132:8080', '192.168.140.133:8080', '192.168.140.134:8080']
