version: '3.8'
services:
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: "otus2023"
    volumes:
      - ./configs/mysql/my-master.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
