version: '3'

services:
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_REPLICATION_USER: replica
      MYSQL_REPLICATION_PASSWORD: replica_password
    ports:
      - "3306:3306"
    volumes:
      - ./configs/mysql/my-master.cnf:/etc/mysql/my.cnf
      - mysql_master_data:/var/lib/mysql
    networks:
      - mysql_net

  mysql_slave:
    image: mysql:8.0
    container_name: mysql_slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - ./configs/mysql/my-slave.cnf:/etc/mysql/my.cnf
      - mysql_slave_data:/var/lib/mysql
    networks:
      - mysql_net

volumes:
  mysql_master_data:
  mysql_slave_data:

networks:
  mysql_net:
    driver: bridge
