global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'apache'
    static_configs:
      - targets: ['192.168.140.133:9117', '192.168.140.134:9117']
  - job_name: 'mysql'
    static_configs:
      - targets: ['192.168.140.133:9104', '192.168.140.134:9104']
